# Generated by Django 5.2.11 on 2026-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_add_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationsysteme',
            options={'ordering': ['-annee_debut', '-id'], 'verbose_name': 'Configuration système', 'verbose_name_plural': 'Configurations système'},
        ),
        migrations.AlterField(
            model_name='configurationsysteme',
            name='annee_debut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='configurationsysteme',
            name='annee_fin',
            field=models.IntegerField(),
        ),
    ]
