# Generated by Django 6.0.3 on 2026-03-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_cloture_stock_mensuelle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cloturestockmensuelle',
            new_name='clotures_st_annee_86d30d_idx',
            old_name='clotures_st_annee_8f676f_idx',
        ),
        migrations.RenameIndex(
            model_name='cloturestockmensuelle',
            new_name='clotures_st_date_ex_9bcdf1_idx',
            old_name='clotures_st_date_ex_55411d_idx',
        ),
    ]
