# Generated by Django 5.2.11 on 2026-02-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mouvements_stock', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='Optionnel pour une entrée. Recommandé pour une sortie (service demandeur).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='requisitions.requisition'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement', 'date_mouvement'], name='mouvements__type_mo_9bc494_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'date_mouvement'], name='mouvements__article_145d46_idx'),
        ),
    ]
