# Generated by Django 5.2.11 on 2026-03-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvements_stock', '0002_initial'),
        ('requisitions', '0005_requisition_traitee_par_recue_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='motif_sortie',
            field=models.TextField(blank=True, default='', help_text='Motif libre pour une sortie manuelle hors réquisition.'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text="Optionnel. Utilisé surtout pour les sorties liées au traitement d'une réquisition.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='requisitions.requisition'),
        ),
    ]
