# Generated by Django 6.0.3 on 2026-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_quantite_par_conditionnement_and_more'),
        ('mouvements_stock', '0003_mouvementstock_motif_sortie_and_more'),
        ('requisitions', '0006_lignerequisition_quantite_demandee_unites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='conditionnement_mouvement',
            field=models.CharField(blank=True, default='Unité', help_text='Conditionnement utilisé pour cette opération : Unité, Boîte, Paquet, etc.', max_length=60),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='quantite_par_conditionnement_mouvement',
            field=models.PositiveIntegerField(default=1, help_text='Nombre d’unités réelles contenues dans 1 conditionnement de l’opération.'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='quantite_unites',
            field=models.PositiveIntegerField(default=1, help_text='Équivalent réel de l’opération en unités de base.'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.PositiveIntegerField(help_text='Quantité saisie dans le conditionnement choisi pour l’opération.'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['conditionnement_mouvement'], name='mouvements__conditi_feff83_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gte', 1)), name='ck_mvt_stock_quantite_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_par_conditionnement_mouvement__gte', 1)), name='ck_mvt_stock_qpc_mvt_ge_1'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_unites__gte', 1)), name='ck_mvt_stock_quantite_unites_ge_1'),
        ),
    ]
