# Generated by Django 5.2.11 on 2026-02-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_rename_articles_ar_nom_fdcbcd_idx_articles_nom_18c025_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseurs',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='AdresseFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('rue', models.CharField(blank=True, default='', max_length=150)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='', max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Adresse fournisseur',
                'verbose_name_plural': 'Adresses fournisseurs',
                'db_table': 'adresses_fournisseurs',
                'ordering': ('pays', 'ville', 'rue', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='ArticleFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_fournisseurs', to='articles.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_articles', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Article-Fournisseur',
                'verbose_name_plural': 'Articles-Fournisseurs',
                'db_table': 'article_fournisseurs',
                'constraints': [models.UniqueConstraint(fields=('article', 'fournisseur'), name='uq_article_fournisseur')],
            },
        ),
    ]
