# Generated by Django 5.2.11 on 2026-02-23 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('niveau', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('app', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('cible_type', models.CharField(blank=True, default='', max_length=120)),
                ('cible_id', models.CharField(blank=True, default='', max_length=64)),
                ('cible_label', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=250)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('succes', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-date_action', '-id'],
            },
        ),
    ]
