# Generated by Django 5.2.11 on 2026-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('GENERATION_RAPPORT', 'Génération rapport')], max_length=80),
        ),
    ]
