# Generated by Django 5.2.11 on 2026-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('GENERATION_RAPPORT', 'Génération rapport'), ('CREATION', 'Création'), ('CONSULTATION', 'Consultation'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('TRAITEMENT', 'Traitement'), ('TRANSFERT', 'Transfert')], max_length=80),
        ),
    ]
