# Generated by Django 5.2.11 on 2026-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditlog_identifiant_saisi'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_identif_53d528_idx',
            old_name='audit_audit_identif_6f4f2d_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('GENERATION_RAPPORT', 'Génération rapport'), ('CREATION', 'Création'), ('CONSULTATION', 'Consultation'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('TRAITEMENT', 'Traitement'), ('TRANSFERT', 'Transfert'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation'), ('ATTRIBUTION_ROLE', 'Attribution rôle'), ('ENVOI_NOTIFICATION', 'Envoi notification'), ('ENVOI_EMAIL_NOTIFICATION', 'Envoi email notification'), ('CONSULTATION_NOTIFICATIONS', 'Consultation notifications'), ('LECTURE_NOTIFICATION', 'Lecture notification')], max_length=80),
        ),
    ]
