# Generated by Django 5.2.11 on 2026-02-23 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_demandeuse', models.CharField(max_length=150)),
                ('date_preparation', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat_requisition', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Rejeté', 'Rejeté'), ('Traité', 'Traité'), ('En attente de modification', 'En attente de modification')], default='En attente', max_length=30)),
                ('motif_global', models.TextField(blank=True, default='')),
                ('remarque', models.TextField(blank=True, default='')),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('transferee_vers_directeur_daa', models.BooleanField(default=False)),
                ('sceau_directeur_daa', models.UUIDField(blank=True, null=True, unique=True)),
                ('date_sceau_directeur_daa', models.DateTimeField(blank=True, null=True)),
                ('demande_modification_motif', models.TextField(blank=True, default='')),
                ('date_demande_modification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réquisition',
                'verbose_name_plural': 'Réquisitions',
                'ordering': ('-date_preparation', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LigneRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField()),
                ('quantite_livree', models.PositiveIntegerField(default=0)),
                ('motif_article', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_requisitions', to='articles.article')),
            ],
            options={
                'verbose_name': 'Ligne de réquisition',
                'verbose_name_plural': 'Lignes de réquisition',
                'ordering': ('id',),
            },
        ),
    ]
