# Generated by Django 5.2.11 on 2026-02-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='demande_modification_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_modif_demandees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='directeur_daa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_a_valider_daa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='directeur_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_a_valider_direction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisition',
            name='soumetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignerequisition',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='requisitions.requisition'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['etat_requisition', 'date_preparation'], name='requisition_etat_re_30322e_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['direction_demandeuse'], name='requisition_directi_ba8796_idx'),
        ),
    ]
