# Generated by Django 5.2.11 on 2026-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_remove_direction_demandeuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='date_transfert_directeur_daa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
