# Generated by Django 6.0.3 on 2026-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_requisition_traitee_par_recue_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignerequisition',
            name='quantite_demandee_unites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignerequisition',
            name='quantite_livree_unites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignerequisition',
            name='unite_demandee',
            field=models.CharField(default='Unité', help_text='Unité choisie par l’utilisateur pour cette ligne : Unité ou conditionnement principal.', max_length=60),
        ),
        migrations.AddField(
            model_name='lignerequisition',
            name='unite_livree',
            field=models.CharField(blank=True, default='', help_text='Unité réellement utilisée lors de la livraison.', max_length=60),
        ),
    ]
