# Generated by Django 5.2.11 on 2026-02-23 18:30

import rapports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rapport',
            name='rapports_rap_type_ra_8f0e51_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rapports_rap_date_ge_7b1d08_idx',
        ),
        migrations.RemoveIndex(
            model_name='rapport',
            name='rapports_rap_annee_m_2d5c1a_idx',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='url_fichier',
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier_html',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=rapports.models._rapport_html_upload_to),
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier_json',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=rapports.models._rapport_json_upload_to),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='format_rapport',
            field=models.CharField(choices=[('HTML', 'HTML (avec graphiques)')], default='HTML', max_length=10),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(choices=[('STOCK_MENSUEL', 'Rapport mensuel (stock & réquisitions)')], max_length=40),
        ),
    ]
