# Generated by Django 5.2.11 on 2026-02-23 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_remove_rapport_rapports_rap_type_ra_8f0e51_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['type_rapport', 'annee', 'mois'], name='rapports_ra_type_ra_c27a85_idx'),
        ),
        migrations.AddIndex(
            model_name='rapport',
            index=models.Index(fields=['consultant', 'date_generation'], name='rapports_ra_consult_443cbf_idx'),
        ),
    ]
