# Generated by Django 5.2.11 on 2026-03-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0003_rapport_rapports_ra_type_ra_c27a85_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
