# Generated by Django 5.2.11 on 2026-02-24 16:16

import utilisateurs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', utilisateurs.models.UtilisateurManager()),
            ],
        ),
    ]
