# Generated by Django 5.2.11 on 2026-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilisateurs', '0005_direction_table_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['direction_affectee'], name='utilisateur_directi_78d6f3_idx'),
        ),
    ]
