# Generated by Django 5.2.11 on 2026-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilisateurs', '0006_utilisateur_utilisateur_directi_78d6f3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_directeur_direction',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['is_directeur_direction'], name='utilisateur_is_dire_fefc84_idx'),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(condition=models.Q(('is_directeur_direction', True), ('direction_affectee__isnull', False)), fields=('direction_affectee',), name='uq_one_directeur_direction_per_direction'),
        ),
    ]
