# Generated by Django 6.0.3 on 2026-03-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_assistant_directeur_and_active_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='utilisateur',
            new_name='utilisateur_directe_e114ee_idx',
            old_name='utilisateur_directeu_4a5d9b_idx',
        ),
        migrations.RenameIndex(
            model_name='utilisateur',
            new_name='utilisateur_is_assi_499be4_idx',
            old_name='utilisateur_is_assis_6d439d_idx',
        ),
    ]
