# Generated by Django 5.2.11 on 2026-02-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='utilisateur_enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.categorie'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['nom'], name='articles_ar_nom_fdcbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['categorie'], name='articles_ar_categor_6bea64_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('stock_initial__gte', 0)), name='ck_article_stock_initial_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actuel__gte', 0)), name='ck_article_stock_actuel_ge_0'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimal__gte', 0)), name='ck_article_stock_minimal_ge_0'),
        ),
    ]
