# Generated by Django 5.2.11 on 2026-02-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_nom_18c025_idx',
            old_name='articles_ar_nom_fdcbcd_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_categor_bbf3cf_idx',
            old_name='articles_ar_categor_6bea64_idx',
        ),
    ]
