# Generated by Django 5.2.11 on 2026-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_articles_ar_nom_fdcbcd_idx_articles_nom_18c025_idx_and_more'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fournisseurs',
            field=models.ManyToManyField(blank=True, related_name='articles', through='fournisseurs.ArticleFournisseur', to='fournisseurs.fournisseur'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categories',
        ),
    ]
