# Generated by Django 6.0.3 on 2026-03-13 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_fournisseurs_alter_article_table_and_more'),
        ('fournisseurs', '0002_remove_articlefournisseur_date_livraison_prevue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantite_par_conditionnement',
            field=models.PositiveIntegerField(default=1, help_text='Nombre d’unités réelles contenues dans 1 conditionnement.'),
        ),
        migrations.AddField(
            model_name='article',
            name='unite_base',
            field=models.CharField(default='Unité', help_text='Unité réelle de calcul du stock. Pour cette première version, elle reste Unité.', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite',
            field=models.CharField(help_text='Conditionnement principal visible par l’utilisateur : Unité, Boîte, Douzaine, Paquet, Carton…', max_length=60),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['unite'], name='articles_unite_bfe5dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_par_conditionnement__gte', 1)), name='ck_article_qte_par_conditionnement_ge_1'),
        ),
    ]
