# Generated by Django 6.0.3 on 2026-03-17 19:51

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_quantite_par_conditionnement_and_more'),
        ('fournisseurs', '0002_remove_articlefournisseur_date_livraison_prevue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(help_text='Nom unique de l’article.', max_length=180),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), name='uq_article_nom_lower'),
        ),
    ]
